CREATE TABLE `t_user` (
	`uid` INT NOT NULL AUTO_INCREMENT,
	`username` CHAR(50) NOT NULL DEFAULT '',
	`password` VARCHAR(45) NOT NULL,
	`name1` VARCHAR(16) NOT NULL,
	`tel` VARCHAR(11) NULL DEFAULT NULL,
	`email` VARCHAR(45) NULL DEFAULT NULL,
	`city` VARCHAR(45) NULL DEFAULT NULL,
	`sex` VARCHAR(45) NULL DEFAULT NULL,
	`account` VARCHAR(16) NULL DEFAULT NULL,
	`mark` INT NULL DEFAULT NULL,
	`checked` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`uid`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1013
;
CREATE TABLE `t_type` (
	`id` INT NOT NULL,
	`type` VARCHAR(50) NOT NULL DEFAULT '',
	`des` VARCHAR(50) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
CREATE TABLE `t_shopcar` (
	`cid` INT NOT NULL AUTO_INCREMENT,
	`uid` INT NOT NULL,
	`id` INT NULL DEFAULT NULL,
	PRIMARY KEY (`cid`),
	INDEX `uid_idx` (`uid`),
	INDEX `gid_idx` (`id`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=19
;
CREATE TABLE `t_order` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` INT NOT NULL DEFAULT '0',
	`goodName` VARCHAR(50) NOT NULL DEFAULT '0',
	`des` VARCHAR(50) NOT NULL DEFAULT '0',
	`number` INT NOT NULL DEFAULT '0',
	`price` INT NOT NULL DEFAULT '0',
	`count` INT NOT NULL DEFAULT '0',
	`checked` VARCHAR(50) NOT NULL DEFAULT '0',
	`delivery` VARCHAR(50) NOT NULL DEFAULT '0',
	`bid` INT NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1063
;
CREATE TABLE `t_message` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`goodName` VARCHAR(50) NOT NULL DEFAULT '0',
	`des` VARCHAR(50) NULL DEFAULT NULL,
	`returnDes` VARCHAR(50) NULL DEFAULT NULL,
	`uid` INT NULL DEFAULT NULL,
	`oid` INT NULL DEFAULT NULL,
	`bid` INT NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=8
;
CREATE TABLE `t_goods` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`goodName` VARCHAR(50) NOT NULL DEFAULT '0',
	`des` VARCHAR(50) NOT NULL DEFAULT '0',
	`headerFilePath` VARCHAR(255) NOT NULL,
	`price` INT NULL DEFAULT NULL,
	`type` VARCHAR(45) NULL DEFAULT NULL,
	`sales` INT NULL DEFAULT NULL,
	`history` INT NULL DEFAULT NULL,
	`mark` VARCHAR(45) NULL DEFAULT NULL,
	`bid` INT NULL DEFAULT NULL,
	`checked` VARCHAR(50) NULL DEFAULT '未审核',
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1031
;
CREATE TABLE `t_business` (
	`bid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(45) NOT NULL,
	`password` VARCHAR(45) NOT NULL,
	`name1` VARCHAR(45) NOT NULL,
	`tel` VARCHAR(11) NULL DEFAULT NULL,
	`email` VARCHAR(45) NULL DEFAULT NULL,
	`city` VARCHAR(45) NULL DEFAULT NULL,
	`sex` VARCHAR(45) NULL DEFAULT NULL,
	`account` VARCHAR(16) NULL DEFAULT NULL,
	`checked` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`bid`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1007
;
CREATE TABLE `t_admin` (
	`aid` INT NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(45) NOT NULL,
	`password` VARCHAR(45) NOT NULL,
	`name` VARCHAR(45) NOT NULL,
	`tel` VARCHAR(11) NULL DEFAULT NULL,
	`email` VARCHAR(45) NULL DEFAULT NULL,
	`city` VARCHAR(45) NULL DEFAULT NULL,
	`sex` VARCHAR(45) NULL DEFAULT NULL,
	`account` VARCHAR(16) NULL DEFAULT NULL,
	PRIMARY KEY (`aid`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
CREATE TABLE `t_address` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` INT NOT NULL DEFAULT '0',
	`username` VARCHAR(50) NOT NULL DEFAULT '',
	`tel` VARCHAR(50) NOT NULL DEFAULT '',
	`address` VARCHAR(50) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1031
;
CREATE TABLE `t_account_user` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`uid` INT NOT NULL DEFAULT '0',
	`account` CHAR(50) NOT NULL DEFAULT '0',
	`password` CHAR(50) NOT NULL DEFAULT '0',
	`money` INT NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	INDEX `uid` (`uid`),
	CONSTRAINT `uid` FOREIGN KEY (`uid`) REFERENCES `t_user` (`uid`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1002
;
CREATE TABLE `t_account_business` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`bid` INT NOT NULL DEFAULT '0',
	`money` INT NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1002
;
