server:
  port: 8888

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    username: root
    password: mxymxy
    url: jdbc:mysql://localhost:3306/2019011441
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
  mapper-locations: classpath:mybatis/Mapper/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true

spring.thymeleaf.content-type: text/html
spring.thymeleaf.cache: false
spring.thymeleaf.mode: LEGACYHTML5

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

